name: Build APK

on:
  workflow_dispatch: # Ручний запуск кнопкою

jobs:
  build:
    runs-on: ubuntu-22.04 # Стабільне оточення

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libreoffice-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install "buildozer>=1.5.0" "cython<3.0.0" virtualenv Kivy

    - name: Accept Android Licenses Automatically
      run: |
        # Попередньо створюємо папку для Android SDK та автоматично приймаємо всі ліцензії Google
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "244d24d21d31d107c4159f4a38780a216d25344e\n24333f1a63b68b44d1d247d4f56f1707b5e633e4\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Build APK with Buildozer
      run: |
        # Запускаем чисту збірку
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VetTrack-AntiLost-APK
        path: bin/*.apk
